# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\diary_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DiaryMainWindow(object):
    def setupUi(self, DiaryMainWindow):
        DiaryMainWindow.setObjectName("DiaryMainWindow")
        DiaryMainWindow.resize(997, 809)
        self.centralwidget = QtWidgets.QWidget(DiaryMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.add_file_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_file_btn.setFont(font)
        self.add_file_btn.setObjectName("add_file_btn")
        self.gridLayout.addWidget(self.add_file_btn, 4, 3, 1, 1)
        self.calendar_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calendar_label.setFont(font)
        self.calendar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.calendar_label.setObjectName("calendar_label")
        self.gridLayout.addWidget(self.calendar_label, 0, 0, 1, 2)
        self.remove_file_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remove_file_btn.setFont(font)
        self.remove_file_btn.setObjectName("remove_file_btn")
        self.gridLayout.addWidget(self.remove_file_btn, 4, 4, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_edit.setFont(font)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 1, 2, 1, 2)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 7, 0, 1, 5)
        self.remove_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.gridLayout.addWidget(self.remove_btn, 15, 4, 1, 1)
        self.all_list_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.all_list_label.setFont(font)
        self.all_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.all_list_label.setObjectName("all_list_label")
        self.gridLayout.addWidget(self.all_list_label, 8, 0, 2, 5)
        self.file_name_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name_line_edit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.file_name_line_edit.setFont(font)
        self.file_name_line_edit.setInputMask("")
        self.file_name_line_edit.setText("")
        self.file_name_line_edit.setDragEnabled(False)
        self.file_name_line_edit.setReadOnly(True)
        self.file_name_line_edit.setPlaceholderText("")
        self.file_name_line_edit.setObjectName("file_name_line_edit")
        self.gridLayout.addWidget(self.file_name_line_edit, 4, 2, 1, 1)
        self.all_list_events = QtWidgets.QListWidget(self.centralwidget)
        self.all_list_events.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.all_list_events.setFont(font)
        self.all_list_events.setObjectName("all_list_events")
        self.gridLayout.addWidget(self.all_list_events, 13, 0, 1, 5)
        self.details_edit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_edit.sizePolicy().hasHeightForWidth())
        self.details_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.details_edit.setFont(font)
        self.details_edit.setObjectName("details_edit")
        self.gridLayout.addWidget(self.details_edit, 3, 2, 1, 3)
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 2, 1, 2)
        self.time_edit = QtWidgets.QTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_edit.setFont(font)
        self.time_edit.setObjectName("time_edit")
        self.gridLayout.addWidget(self.time_edit, 1, 4, 1, 1)
        self.details_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.details_label.setFont(font)
        self.details_label.setAlignment(QtCore.Qt.AlignCenter)
        self.details_label.setObjectName("details_label")
        self.gridLayout.addWidget(self.details_label, 2, 2, 1, 2)
        self.important_check_box = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.important_check_box.setFont(font)
        self.important_check_box.setObjectName("important_check_box")
        self.gridLayout.addWidget(self.important_check_box, 5, 3, 1, 1)
        self.choice_color_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choice_color_btn.setFont(font)
        self.choice_color_btn.setObjectName("choice_color_btn")
        self.gridLayout.addWidget(self.choice_color_btn, 5, 4, 1, 1)
        self.open_detalies_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.open_detalies_btn.setFont(font)
        self.open_detalies_btn.setObjectName("open_detalies_btn")
        self.gridLayout.addWidget(self.open_detalies_btn, 15, 0, 1, 2)
        self.calendar_edit = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar_edit.setObjectName("calendar_edit")
        self.gridLayout.addWidget(self.calendar_edit, 1, 0, 4, 2)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 0, 4, 1, 1)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.error_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.error_label.setFont(font)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.gridLayout.addWidget(self.error_label, 15, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 0, 1, 1)
        self.sorted_combo_box = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sorted_combo_box.setFont(font)
        self.sorted_combo_box.setObjectName("sorted_combo_box")
        self.sorted_combo_box.addItem("")
        self.sorted_combo_box.addItem("")
        self.gridLayout.addWidget(self.sorted_combo_box, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 1, 1, 1)
        self.filter_combo_box = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filter_combo_box.setFont(font)
        self.filter_combo_box.setObjectName("filter_combo_box")
        self.filter_combo_box.addItem("")
        self.gridLayout.addWidget(self.filter_combo_box, 12, 1, 1, 1)
        self.today_date_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.today_date_btn.setFont(font)
        self.today_date_btn.setObjectName("today_date_btn")
        self.gridLayout.addWidget(self.today_date_btn, 5, 0, 1, 2)
        DiaryMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DiaryMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DiaryMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DiaryMainWindow)
        self.statusbar.setObjectName("statusbar")
        DiaryMainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(DiaryMainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSettings = QtWidgets.QAction(DiaryMainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtWidgets.QAction(DiaryMainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFIle.addAction(self.actionExport)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DiaryMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DiaryMainWindow)

    def retranslateUi(self, DiaryMainWindow):
        _translate = QtCore.QCoreApplication.translate
        DiaryMainWindow.setWindowTitle(_translate("DiaryMainWindow", "MainWindow"))
        self.add_file_btn.setText(_translate("DiaryMainWindow", "Файл..."))
        self.calendar_label.setText(_translate("DiaryMainWindow", "Дата"))
        self.remove_file_btn.setText(_translate("DiaryMainWindow", "Удалить"))
        self.add_btn.setText(_translate("DiaryMainWindow", "Добавить"))
        self.remove_btn.setText(_translate("DiaryMainWindow", "Удалить"))
        self.all_list_label.setText(_translate("DiaryMainWindow", "Все события"))
        self.details_edit.setHtml(_translate("DiaryMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.name_label.setText(_translate("DiaryMainWindow", "Название"))
        self.details_label.setText(_translate("DiaryMainWindow", "Описание"))
        self.important_check_box.setText(_translate("DiaryMainWindow", "Отметить как важное"))
        self.choice_color_btn.setText(_translate("DiaryMainWindow", "Цвет..."))
        self.open_detalies_btn.setText(_translate("DiaryMainWindow", "Открыть"))
        self.time_label.setText(_translate("DiaryMainWindow", "Время"))
        self.label.setText(_translate("DiaryMainWindow", "Сортировка:"))
        self.sorted_combo_box.setItemText(0, _translate("DiaryMainWindow", "Дата и время"))
        self.sorted_combo_box.setItemText(1, _translate("DiaryMainWindow", "Название"))
        self.label_2.setText(_translate("DiaryMainWindow", "Фильтр:"))
        self.filter_combo_box.setItemText(0, _translate("DiaryMainWindow", "Все"))
        self.today_date_btn.setText(_translate("DiaryMainWindow", "Текущая дата"))
        self.menuFIle.setTitle(_translate("DiaryMainWindow", "Файл"))
        self.menuHelp.setTitle(_translate("DiaryMainWindow", "Помошь"))
        self.actionExport.setText(_translate("DiaryMainWindow", "Экспорт"))
        self.actionExport.setShortcut(_translate("DiaryMainWindow", "Ctrl+E"))
        self.actionSettings.setText(_translate("DiaryMainWindow", "Настройки"))
        self.actionSettings.setShortcut(_translate("DiaryMainWindow", "Ctrl+S"))
        self.actionHelp.setText(_translate("DiaryMainWindow", "О Приложении"))

