# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(425, 451)
        self.gridLayout = QtWidgets.QGridLayout(SettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.default_settings_load_btn = QtWidgets.QPushButton(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_settings_load_btn.sizePolicy().hasHeightForWidth())
        self.default_settings_load_btn.setSizePolicy(sizePolicy)
        self.default_settings_load_btn.setObjectName("default_settings_load_btn")
        self.gridLayout.addWidget(self.default_settings_load_btn, 2, 1, 1, 1)
        self.settings_button_box = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.settings_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.settings_button_box.setObjectName("settings_button_box")
        self.gridLayout.addWidget(self.settings_button_box, 4, 0, 1, 2)
        self.settings_groupBox = QtWidgets.QGroupBox(SettingsDialog)
        self.settings_groupBox.setObjectName("settings_groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.settings_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.groupBox = QtWidgets.QGroupBox(self.settings_groupBox)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.font_label = QtWidgets.QLabel(self.groupBox)
        self.font_label.setObjectName("font_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.font_label)
        self.font_main_combo_box = QtWidgets.QFontComboBox(self.groupBox)
        self.font_main_combo_box.setObjectName("font_main_combo_box")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.font_main_combo_box)
        self.font_size_label = QtWidgets.QLabel(self.groupBox)
        self.font_size_label.setObjectName("font_size_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.font_size_label)
        self.font_size_main_combo_box = QtWidgets.QComboBox(self.groupBox)
        self.font_size_main_combo_box.setObjectName("font_size_main_combo_box")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.font_size_main_combo_box.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.font_size_main_combo_box)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.settings_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.font_details_combo_box = QtWidgets.QFontComboBox(self.groupBox_2)
        self.font_details_combo_box.setObjectName("font_details_combo_box")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.font_details_combo_box)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.font_size_details_combo_box = QtWidgets.QComboBox(self.groupBox_2)
        self.font_size_details_combo_box.setObjectName("font_size_details_combo_box")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.font_size_details_combo_box.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.font_size_details_combo_box)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.settings_groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.date_format_label = QtWidgets.QLabel(self.groupBox_3)
        self.date_format_label.setObjectName("date_format_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.date_format_label)
        self.date_format_combo_box = QtWidgets.QComboBox(self.groupBox_3)
        self.date_format_combo_box.setObjectName("date_format_combo_box")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.date_format_combo_box.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.date_format_combo_box)
        self.time_format_label = QtWidgets.QLabel(self.groupBox_3)
        self.time_format_label.setObjectName("time_format_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.time_format_label)
        self.time_format_combo_box = QtWidgets.QComboBox(self.groupBox_3)
        self.time_format_combo_box.setObjectName("time_format_combo_box")
        self.time_format_combo_box.addItem("")
        self.time_format_combo_box.addItem("")
        self.time_format_combo_box.addItem("")
        self.time_format_combo_box.addItem("")
        self.time_format_combo_box.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.time_format_combo_box)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.color_important_event_label = QtWidgets.QLabel(self.settings_groupBox)
        self.color_important_event_label.setObjectName("color_important_event_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.color_important_event_label)
        self.color_important_event_btn = QtWidgets.QToolButton(self.settings_groupBox)
        self.color_important_event_btn.setObjectName("color_important_event_btn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.color_important_event_btn)
        self.sorting_defoult_label = QtWidgets.QLabel(self.settings_groupBox)
        self.sorting_defoult_label.setObjectName("sorting_defoult_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sorting_defoult_label)
        self.sotring_default_combo_box = QtWidgets.QComboBox(self.settings_groupBox)
        self.sotring_default_combo_box.setObjectName("sotring_default_combo_box")
        self.sotring_default_combo_box.addItem("")
        self.sotring_default_combo_box.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sotring_default_combo_box)
        self.auto_delete_event_label = QtWidgets.QLabel(self.settings_groupBox)
        self.auto_delete_event_label.setObjectName("auto_delete_event_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.auto_delete_event_label)
        self.auto_delete_event_check_box = QtWidgets.QCheckBox(self.settings_groupBox)
        self.auto_delete_event_check_box.setText("")
        self.auto_delete_event_check_box.setObjectName("auto_delete_event_check_box")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.auto_delete_event_check_box)
        self.gridLayout.addWidget(self.settings_groupBox, 0, 0, 1, 2)

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Form"))
        self.default_settings_load_btn.setText(_translate("SettingsDialog", "По умолчанию"))
        self.settings_groupBox.setTitle(_translate("SettingsDialog", "Настройки"))
        self.groupBox.setTitle(_translate("SettingsDialog", "Шрифт списка событий"))
        self.font_label.setText(_translate("SettingsDialog", "Шрифт"))
        self.font_size_label.setText(_translate("SettingsDialog", "Размер шрифта"))
        self.font_size_main_combo_box.setItemText(0, _translate("SettingsDialog", "8"))
        self.font_size_main_combo_box.setItemText(1, _translate("SettingsDialog", "10"))
        self.font_size_main_combo_box.setItemText(2, _translate("SettingsDialog", "12"))
        self.font_size_main_combo_box.setItemText(3, _translate("SettingsDialog", "14"))
        self.font_size_main_combo_box.setItemText(4, _translate("SettingsDialog", "16"))
        self.font_size_main_combo_box.setItemText(5, _translate("SettingsDialog", "18"))
        self.font_size_main_combo_box.setItemText(6, _translate("SettingsDialog", "20"))
        self.font_size_main_combo_box.setItemText(7, _translate("SettingsDialog", "22"))
        self.font_size_main_combo_box.setItemText(8, _translate("SettingsDialog", "24"))
        self.font_size_main_combo_box.setItemText(9, _translate("SettingsDialog", "26"))
        self.font_size_main_combo_box.setItemText(10, _translate("SettingsDialog", "28"))
        self.font_size_main_combo_box.setItemText(11, _translate("SettingsDialog", "30"))
        self.font_size_main_combo_box.setItemText(12, _translate("SettingsDialog", "32"))
        self.font_size_main_combo_box.setItemText(13, _translate("SettingsDialog", "34"))
        self.font_size_main_combo_box.setItemText(14, _translate("SettingsDialog", "36"))
        self.font_size_main_combo_box.setItemText(15, _translate("SettingsDialog", "38"))
        self.font_size_main_combo_box.setItemText(16, _translate("SettingsDialog", "40"))
        self.groupBox_2.setTitle(_translate("SettingsDialog", "Шрифт подробностей события"))
        self.label_2.setText(_translate("SettingsDialog", "Шрифт"))
        self.label.setText(_translate("SettingsDialog", "Размер шрифта"))
        self.font_size_details_combo_box.setItemText(0, _translate("SettingsDialog", "8"))
        self.font_size_details_combo_box.setItemText(1, _translate("SettingsDialog", "10"))
        self.font_size_details_combo_box.setItemText(2, _translate("SettingsDialog", "12"))
        self.font_size_details_combo_box.setItemText(3, _translate("SettingsDialog", "14"))
        self.font_size_details_combo_box.setItemText(4, _translate("SettingsDialog", "16"))
        self.font_size_details_combo_box.setItemText(5, _translate("SettingsDialog", "18"))
        self.font_size_details_combo_box.setItemText(6, _translate("SettingsDialog", "20"))
        self.font_size_details_combo_box.setItemText(7, _translate("SettingsDialog", "22"))
        self.font_size_details_combo_box.setItemText(8, _translate("SettingsDialog", "24"))
        self.font_size_details_combo_box.setItemText(9, _translate("SettingsDialog", "26"))
        self.font_size_details_combo_box.setItemText(10, _translate("SettingsDialog", "28"))
        self.font_size_details_combo_box.setItemText(11, _translate("SettingsDialog", "30"))
        self.font_size_details_combo_box.setItemText(12, _translate("SettingsDialog", "32"))
        self.font_size_details_combo_box.setItemText(13, _translate("SettingsDialog", "34"))
        self.font_size_details_combo_box.setItemText(14, _translate("SettingsDialog", "36"))
        self.font_size_details_combo_box.setItemText(15, _translate("SettingsDialog", "38"))
        self.font_size_details_combo_box.setItemText(16, _translate("SettingsDialog", "40"))
        self.groupBox_3.setTitle(_translate("SettingsDialog", "Экспорт"))
        self.date_format_label.setText(_translate("SettingsDialog", "Формат даты"))
        self.date_format_combo_box.setItemText(0, _translate("SettingsDialog", "dd/mm/yy"))
        self.date_format_combo_box.setItemText(1, _translate("SettingsDialog", "mm/dd/yy"))
        self.date_format_combo_box.setItemText(2, _translate("SettingsDialog", "dd m yy"))
        self.date_format_combo_box.setItemText(3, _translate("SettingsDialog", "d mm yy"))
        self.date_format_combo_box.setItemText(4, _translate("SettingsDialog", "d mmm yy"))
        self.date_format_combo_box.setItemText(5, _translate("SettingsDialog", "d mmmm yy"))
        self.date_format_combo_box.setItemText(6, _translate("SettingsDialog", "ddd mmm"))
        self.date_format_combo_box.setItemText(7, _translate("SettingsDialog", "ddd mmm yyyy"))
        self.date_format_combo_box.setItemText(8, _translate("SettingsDialog", "dddd d mmm"))
        self.date_format_combo_box.setItemText(9, _translate("SettingsDialog", "mmmm d"))
        self.date_format_combo_box.setItemText(10, _translate("SettingsDialog", "mmmm d ddd"))
        self.time_format_label.setText(_translate("SettingsDialog", "Формат времени"))
        self.time_format_combo_box.setItemText(0, _translate("SettingsDialog", "hh:mm"))
        self.time_format_combo_box.setItemText(1, _translate("SettingsDialog", "hh:mm:ss"))
        self.time_format_combo_box.setItemText(2, _translate("SettingsDialog", "hh:mm:ss.000"))
        self.time_format_combo_box.setItemText(3, _translate("SettingsDialog", "hh:00"))
        self.time_format_combo_box.setItemText(4, _translate("SettingsDialog", "hh"))
        self.color_important_event_label.setText(_translate("SettingsDialog", "Цвет важных событий"))
        self.color_important_event_btn.setText(_translate("SettingsDialog", "..."))
        self.sorting_defoult_label.setText(_translate("SettingsDialog", "Сортировка по умолчанию"))
        self.sotring_default_combo_box.setItemText(0, _translate("SettingsDialog", "Дата и время"))
        self.sotring_default_combo_box.setItemText(1, _translate("SettingsDialog", "Название"))
        self.auto_delete_event_label.setText(_translate("SettingsDialog", "Автоматическое удаление событий"))
